openapi: 3.2.0
info:
  title: api Evaluation Service API
  version: 1.47.0
servers:
- url: http://localhost:8080
security:
- bearerAuth: []
tags:
- name: EvaluationService
paths:
  /evaluate/v1/batch:
    post:
      tags:
      - EvaluationService
      operationId: evaluateBatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchEvaluationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchEvaluationResponse'
      summary: Evaluate batch
      x-summary-source: derived
  /evaluate/v1/boolean:
    post:
      tags:
      - EvaluationService
      operationId: evaluateBoolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooleanEvaluationResponse'
      summary: Evaluate boolean
      x-summary-source: derived
  /evaluate/v1/variant:
    post:
      tags:
      - EvaluationService
      operationId: evaluateVariant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariantEvaluationResponse'
      summary: Evaluate variant
      x-summary-source: derived
components:
  schemas:
    BatchEvaluationResponse:
      type: object
      properties:
        requestId:
          type: string
        responses:
          type: array
          items:
            $ref: '#/components/schemas/EvaluationResponse'
        requestDurationMillis:
          type: number
          format: double
    EvaluationResponse:
      type: object
      properties:
        type:
          enum:
          - VARIANT_EVALUATION_RESPONSE_TYPE
          - BOOLEAN_EVALUATION_RESPONSE_TYPE
          - ERROR_EVALUATION_RESPONSE_TYPE
          type: string
          format: enum
        booleanResponse:
          $ref: '#/components/schemas/BooleanEvaluationResponse'
        variantResponse:
          $ref: '#/components/schemas/VariantEvaluationResponse'
        errorResponse:
          $ref: '#/components/schemas/ErrorEvaluationResponse'
    BooleanEvaluationResponse:
      type: object
      properties:
        enabled:
          type: boolean
        reason:
          enum:
          - UNKNOWN_EVALUATION_REASON
          - FLAG_DISABLED_EVALUATION_REASON
          - MATCH_EVALUATION_REASON
          - DEFAULT_EVALUATION_REASON
          type: string
          format: enum
        requestId:
          type: string
        requestDurationMillis:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
        flagKey:
          type: string
        segmentKeys:
          type: array
          items:
            type: string
    BatchEvaluationRequest:
      required:
      - requests
      type: object
      properties:
        requestId:
          type: string
        requests:
          type: array
          items:
            $ref: '#/components/schemas/EvaluationRequest'
        reference:
          type: string
    EvaluationRequest:
      required:
      - namespaceKey
      - flagKey
      - entityId
      - context
      type: object
      properties:
        requestId:
          type: string
        namespaceKey:
          type: string
        flagKey:
          type: string
        entityId:
          type: string
        context:
          type: object
          additionalProperties:
            type: string
        reference:
          type: string
    ErrorEvaluationResponse:
      type: object
      properties:
        flagKey:
          type: string
        namespaceKey:
          type: string
        reason:
          enum:
          - UNKNOWN_ERROR_EVALUATION_REASON
          - NOT_FOUND_ERROR_EVALUATION_REASON
          type: string
          format: enum
    VariantEvaluationResponse:
      type: object
      properties:
        match:
          type: boolean
        segmentKeys:
          type: array
          items:
            type: string
        reason:
          enum:
          - UNKNOWN_EVALUATION_REASON
          - FLAG_DISABLED_EVALUATION_REASON
          - MATCH_EVALUATION_REASON
          - DEFAULT_EVALUATION_REASON
          type: string
          format: enum
        variantKey:
          type: string
        variantAttachment:
          type: string
        requestId:
          type: string
        requestDurationMillis:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
        flagKey:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    jwtAuth:
      type: http
      scheme: JWT
