openapi: 3.2.0
info:
  title: api Authentication Method OIDC Service API
  version: 1.47.0
servers:
- url: http://localhost:8080
security:
- bearerAuth: []
tags:
- name: AuthenticationMethodOIDCService
paths:
  /auth/v1/method/oidc/{provider}/authorize:
    get:
      tags:
      - AuthenticationMethodOIDCService
      operationId: oidcAuthorizeURL
      parameters:
      - name: provider
        in: path
        required: true
        schema:
          type: string
      - name: state
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizeURLResponse'
      summary: Oidc authorize URL
      x-summary-source: derived
  /auth/v1/method/oidc/{provider}/callback:
    get:
      tags:
      - AuthenticationMethodOIDCService
      operationId: oidcCallback
      parameters:
      - name: provider
        in: path
        required: true
        schema:
          type: string
      - name: code
        in: query
        schema:
          type: string
      - name: state
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackResponse'
      summary: Oidc callback
      x-summary-source: derived
components:
  schemas:
    Authentication:
      type: object
      properties:
        id:
          type: string
        method:
          enum:
          - METHOD_NONE
          - METHOD_TOKEN
          - METHOD_OIDC
          - METHOD_KUBERNETES
          - METHOD_GITHUB
          - METHOD_JWT
          - METHOD_CLOUD
          type: string
          format: enum
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        metadata:
          type: object
          additionalProperties:
            type: string
    CallbackResponse:
      type: object
      properties:
        clientToken:
          type: string
        authentication:
          $ref: '#/components/schemas/Authentication'
    AuthorizeURLResponse:
      type: object
      properties:
        authorizeUrl:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    jwtAuth:
      type: http
      scheme: JWT
